version: '3.1'
services:
  phx:
    image: codigobicentenario/phoenix:ubuntu
    ports:
      - "${PHX_HOST_PORT:-9001}:${PHX_PORT:-4000}"
    volumes:
      - ./src:/app/src
      - ./src/_build/prod/rel:/app/src/_build/prod/rel
      - phx.deps:/app/src/deps
      - phx.builds:/app/src/_build
    depends_on:
      - postgres
    environment:
      - MIX_ENV=${ENV:-dev}
      - PHX_PORT=${PHX_PORT:-4000}
      - PHX_URL=${PHX_HOST:-localhost}
      - PHX_SECRET_KEY_BASE=${PHX_SECRET_KEY_BASE:-default}
      - PG_INVITES_URL=ecto://postgres:postgres@postgres/invites_${ENV:-dev}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-default}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-default}

      - FONTS_BUCKET=${FONTS_BUCKET:-default}
      - MESSAGES_BUCKET=${MESSAGES_BUCKET:-default}

    working_dir: /app/src
    command: mix phx.server

  phx.release:
    build: .
    ports:
       - "${PHX_HOST_PORT:-9001}:${PHX_PORT:-4000}"
    depends_on:
      - postgres
    environment:
      - REPLACE_OS_VARS=true
      - PHX_PORT=${PHX_PORT:-4000}
      - PHX_URL=${PHX_URL:-localhost}
      - PHX_SECRET_KEY_BASE=${PHX_SECRET_KEY_BASE:-default}
      - PG_INVITES_URL=ecto://postgres:postgres@postgres/invites_${ENV:-dev}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-default}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-default}

      - FONTS_BUCKET=${FONTS_BUCKET:-default}
      - MESSAGES_BUCKET=${MESSAGES_BUCKET:-default}

  postgres:
    image: postgres:9.6.4

volumes:
  phx.deps:
  phx.builds:
